linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US
  skip-files:
    - app/internal/**/*_test.go


linters:
  disable-all: true
  enable:
    - goimports
    - unused
    - errcheck
    # - gocognit
    # - gocyclo
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace