---
name: Bug report
about: Create a report to help us improve
---

<!--
Thanks for contributing to the PokéAPI project. To make sure we're effective, please check the following:

- Make sure your issue hasn't already been submitted on the issues tab. (It has search functionality!)
- Provide a clear description of the issue.
- Provide a clear description of the steps to reproduce.
- Provide a clear description of the expected behavior.

Thank you!
-->

Steps to Reproduce:

1.
2.
