swagger: "2.0"
info:
  title: MH-API
  description: モンハンAPIゲートウェイ
  version: 1.0.0
securityDefinitions:
  auth0_jwk:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://dev-8pmkik25y0obts0r.us.auth0.com/"
    x-google-jwks_uri: "https://dev-8pmkik25y0obts0r.us.auth0.com/.well-known/jwks.json"
    x-google-audience: "https://mh-api-v2-8aznfogc.an.gateway.dev"

schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://mh-api-xpzdc5i4rq-an.a.run.app
paths:
  /v1/health:
    get:
      summary: ヘルスチェック
      operationId: health
      responses:
        "200":
          description: ヘルスチェック
          schema:
            type: string
  /v1/monsters:
    get:
      description: 全てのモンスター情報を取得する
      operationId: getMonsters
      responses:
        "200":
          description: モンスター情報の取得に成功
          schema:
            type: object
        "404":
          description: モンスターが見つかりません
          schema:
            type: object
        "500":
          description: モンスター情報の取得に失敗
          schema:
            type: object
    post:
      summary: モンスターの情報を追加する
      operationId: createMonsters
      parameters:
        - name: requestJson
          in: body
          required: true
          schema:
            type: object
            required:
              - name
              - desc
              - location
              - specify
              - weakness_attack
              - weakness_element
            properties:
              name:
                type: string
              desc:
                type: string
              location:
                type: string
              specify:
                type: string
              weakness_attack:
                type: string
              weakness_element:
                type: string
      responses:
        "200":
          description: モンスターの情報の登録に成功
          schema:
            type: object
        "403":
          description: 認証失敗
          schema:
            type: object
        "500":
          description: サーバエラーにより更新失敗
          schema:
            type: object
      security:
        - sa_auth: []
  /v1/monsters/{requestId}:
    get:
      summary: idのモンスター情報を取得する
      operationId: requestId
      parameters:
        - name: requestId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: モンスター情報の取得に成功
          schema:
            type: object
        "404":
          description: モンスターが見つかりません
          schema:
            type: object
        "500":
          description: モンスター情報の取得に失敗
          schema:
            type: object
    patch:
      summary: モンスターの情報を更新する
      operationId: updateMonsters
      security:
        - sa_auth: []
      parameters:
        - name: requestId
          in: path
          required: true
          type: string
        - name: requestJson
          in: body
          required: true
          schema:
            type: object
            required:
              - name
              - desc
              - location
              - specify
              - weakness_attack
              - weakness_element
            properties:
              name:
                type: string
              desc:
                type: string
              location:
                type: string
              specify:
                type: string
              weakness_attack:
                type: string
              weakness_element:
                type: string
      responses:
        "200":
          description: モンスターの情報の更新に成功
          schema:
            type: object
        "403":
          description: 認証失敗
          schema:
            type: object
        "500":
          description: サーバエラーにより更新失敗
          schema:
            type: object
    delete:
      summary: モンスターの情報を削除する
      operationId: deleteMonsters
      security:
        - sa_auth: []
      parameters:
        - name: requestId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: モンスターの情報の削除に成功
          schema:
            type: object
        "403":
          description: 認証失敗
          schema:
            type: object
        "500":
          description: サーバエラーにより削除失敗
          schema:
            type: object
  /v1/monsters/json:
    post:
      summary: モンスターの情報をjsonで一括追加する
      operationId: createMonstersJson
      security:
        - sa_auth: []
      parameters:
        - name: requestJson
          in: body
          required: true
          schema:
            type: object
            required:
              - name
              - desc
              - location
              - specify
              - weakness_attack
              - weakness_element
            properties:
              name:
                type: string
              desc:
                type: string
              location:
                type: string
              specify:
                type: string
              weakness_attack:
                type: string
              weakness_element:
                type: string
      responses:
        "200":
          description: モンスターの情報の登録に成功
          schema:
            type: object
        "403":
          description: 認証失敗
          schema:
            type: object
        "500":
          description: サーバエラーにより更新失敗
          schema:
            type: object
