// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/items": {
            "get": {
                "description": "アイテムを検索して、条件に合致するアイテムを複数件取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アイテム検索"
                ],
                "summary": "アイテム検索（複数件）",
                "parameters": [
                    {
                        "type": "string",
                        "name": "item_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "item_name_kana",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "monster_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/item.Items"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    }
                }
            }
        },
        "/items/:itemId": {
            "get": {
                "description": "アイテムを検索して、条件に合致するアイテムを1件取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アイテム検索"
                ],
                "summary": "アイテム検索（1件）",
                "parameters": [
                    {
                        "type": "string",
                        "name": "item_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "item_name_kana",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "monster_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/item.Item"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    }
                }
            }
        },
        "/items/monsters": {
            "get": {
                "description": "指定のアイテムが取得可能なモンスターの一覧",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "アイテム検索"
                ],
                "summary": "アイテム検索（モンスター別）",
                "parameters": [
                    {
                        "type": "string",
                        "name": "item_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "item_name_kana",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "monster_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/item.ItemsByMonster"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/item.MessageResponse"
                        }
                    }
                }
            }
        },
        "/monsters": {
            "get": {
                "description": "モンスターを検索して、条件に合致するモンスターを複数件取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "モンスター検索"
                ],
                "summary": "モンスター検索（複数件）",
                "parameters": [
                    {
                        "type": "string",
                        "name": "MonsterIds",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "MonsterName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/monster.Monsters"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/monster.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/monster.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/monster.MessageResponse"
                        }
                    }
                }
            }
        },
        "/monsters/:monsterid": {
            "get": {
                "description": "モンスターを検索して、条件に合致するモンスターを1件取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "モンスター検索"
                ],
                "summary": "モンスター検索（1件）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "モンスターID",
                        "name": "request",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/monster.Monster"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/monster.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/monster.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/monster.MessageResponse"
                        }
                    }
                }
            }
        },
        "/weapons": {
            "get": {
                "description": "武器を検索して、条件に合致する武器を複数件取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "武器検索"
                ],
                "summary": "武器検索（複数件）",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "monster_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name_kana",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/weapon.Weapon"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/weapon.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/weapon.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/weapon.MessageResponse"
                        }
                    }
                }
            }
        },
        "/weapons/:bgmid": {
            "get": {
                "description": "武器を検索して、条件に合致する武器を1件取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "武器検索"
                ],
                "summary": "武器検索（1件）",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "monster_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name_kana",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/weapon.Weapon"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/weapon.MessageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/weapon.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/weapon.MessageResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "item.Item": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/item.ResponseJson"
                }
            }
        },
        "item.Items": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/item.ResponseJson"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "item.ItemsByMonster": {
            "type": "object",
            "properties": {
                "item_id": {
                    "type": "string"
                },
                "item_name": {
                    "type": "string"
                },
                "monsters": {
                    "$ref": "#/definitions/monster.Monsters"
                }
            }
        },
        "item.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "item.ResponseJson": {
            "type": "object",
            "properties": {
                "item_id": {
                    "type": "string"
                },
                "item_name": {
                    "type": "string"
                }
            }
        },
        "monster.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "monster.Monster": {
            "type": "object",
            "properties": {
                "monster": {
                    "$ref": "#/definitions/monster.ResponseJson"
                }
            }
        },
        "monster.Monsters": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "monsters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/monster.ResponseJson"
                    }
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "monster.Music": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "monster.Ranking": {
            "type": "object",
            "properties": {
                "ranking": {
                    "type": "string"
                },
                "vote_year": {
                    "type": "string"
                }
            }
        },
        "monster.ResponseJson": {
            "type": "object",
            "properties": {
                "another_name": {
                    "description": "モンスター別名",
                    "type": "string"
                },
                "bgm": {
                    "description": "BGM",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/monster.Music"
                    }
                },
                "category": {
                    "description": "モンスターのカテゴリ",
                    "type": "string"
                },
                "first_weak_attack": {
                    "description": "最有効弱点",
                    "type": "string"
                },
                "first_weak_element": {
                    "description": "最有効属性",
                    "type": "string"
                },
                "image_url": {
                    "description": "モンスター画像URL",
                    "type": "string"
                },
                "location": {
                    "description": "モンスターの出現場所",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "monster_id": {
                    "description": "モンスターID",
                    "type": "string"
                },
                "name": {
                    "description": "モンスター名",
                    "type": "string"
                },
                "ranking": {
                    "description": "人気投票ランキング",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/monster.Ranking"
                    }
                },
                "second_weak_attack": {
                    "description": "2番目に有効な弱点",
                    "type": "string"
                },
                "second_weak_element": {
                    "description": "2番目に有効な属性",
                    "type": "string"
                },
                "title": {
                    "description": "登場作品",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "weakness_attack": {
                    "description": "弱点肉質（物理）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/monster.Weakness_attack"
                    }
                },
                "weakness_element": {
                    "description": "弱点肉質（属性）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/monster.Weakness_element"
                    }
                }
            }
        },
        "monster.Weakness_attack": {
            "type": "object",
            "properties": {
                "blow": {
                    "type": "string"
                },
                "bullet": {
                    "type": "string"
                },
                "slashing": {
                    "type": "string"
                }
            }
        },
        "monster.Weakness_element": {
            "type": "object",
            "properties": {
                "dragon": {
                    "type": "string"
                },
                "fire": {
                    "type": "string"
                },
                "ice": {
                    "type": "string"
                },
                "thunder": {
                    "type": "string"
                },
                "water": {
                    "type": "string"
                }
            }
        },
        "weapon.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "weapon.ResponseJson": {
            "type": "object",
            "properties": {
                "attack": {
                    "type": "string"
                },
                "critical": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "elemant_attaxk": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "monster_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rare": {
                    "type": "string"
                },
                "shapness": {
                    "type": "string"
                }
            }
        },
        "weapon.Weapon": {
            "type": "object",
            "properties": {
                "monster": {
                    "$ref": "#/definitions/weapon.ResponseJson"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.1.0",
	Host:             "https://mh-api-v2-8aznfogc.an.gateway.dev/",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "MH-API",
	Description:      "モンスターハンターAPI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
