basePath: /v1
definitions:
  armor.ArmorDetailResponse:
    properties:
      defense:
        type: integer
      id:
        type: string
      name:
        type: string
      required:
        items:
          $ref: '#/definitions/armor.RequiredItemResponse'
        type: array
      resistance:
        $ref: '#/definitions/armor.ResistanceResponse'
      skills:
        items:
          $ref: '#/definitions/armor.SkillResponse'
        type: array
      slot:
        type: string
    type: object
  armor.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  armor.ListArmorsResponse:
    properties:
      armors:
        items:
          $ref: '#/definitions/armor.ArmorDetailResponse'
        type: array
    type: object
  armor.RequiredItemResponse:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  armor.ResistanceResponse:
    properties:
      dragon:
        type: integer
      fire:
        type: integer
      ice:
        type: integer
      lightning:
        type: integer
      water:
        type: integer
    type: object
  armor.SkillResponse:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  item.Item:
    properties:
      item:
        $ref: '#/definitions/item.ResponseJson'
    type: object
  item.Items:
    properties:
      items:
        items:
          $ref: '#/definitions/item.ResponseJson'
        type: array
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  item.ItemsByMonster:
    properties:
      items:
        items:
          $ref: '#/definitions/item.Item'
        type: array
      monster_id:
        type: string
      monster_name:
        type: string
    type: object
  item.MessageResponse:
    properties:
      message:
        type: string
    type: object
  item.ResponseJson:
    properties:
      item_id:
        type: string
      item_name:
        type: string
    type: object
  monster.MessageResponse:
    properties:
      message:
        type: string
    type: object
  monster.Monster:
    properties:
      monster:
        $ref: '#/definitions/monster.ResponseJson'
    type: object
  monster.Monsters:
    properties:
      limit:
        type: integer
      monsters:
        items:
          $ref: '#/definitions/monster.ResponseJson'
        type: array
      offset:
        type: integer
      total:
        type: integer
    type: object
  monster.Music:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  monster.Ranking:
    properties:
      ranking:
        type: string
      vote_year:
        type: string
    type: object
  monster.ResponseJson:
    properties:
      another_name:
        description: モンスター別名
        type: string
      bgm:
        description: BGM
        items:
          $ref: '#/definitions/monster.Music'
        type: array
      category:
        description: モンスターのカテゴリ
        type: string
      description:
        description: モンスターの説明
        type: string
      element:
        description: モンスターの属性
        type: string
      first_weak_attack:
        description: 最有効弱点
        type: string
      first_weak_element:
        description: 最有効属性
        type: string
      image_url:
        description: モンスター画像URL
        type: string
      location:
        description: モンスターの出現場所
        items:
          type: string
        type: array
      monster_id:
        description: モンスターID
        type: string
      name:
        description: モンスター名
        type: string
      name_en:
        description: モンスター名（英語）
        type: string
      ranking:
        description: 人気投票ランキング
        items:
          $ref: '#/definitions/monster.Ranking'
        type: array
      second_weak_attack:
        description: 2番目に有効な弱点
        type: string
      second_weak_element:
        description: 2番目に有効な属性
        type: string
      title:
        description: 登場作品
        items:
          type: string
        type: array
      weakness_attack:
        description: 弱点肉質（物理）
        items:
          $ref: '#/definitions/monster.Weakness_attack'
        type: array
      weakness_element:
        description: 弱点肉質（属性）
        items:
          $ref: '#/definitions/monster.Weakness_element'
        type: array
    type: object
  monster.Weakness_attack:
    properties:
      blow:
        type: string
      bullet:
        type: string
      slashing:
        type: string
    type: object
  monster.Weakness_element:
    properties:
      dragon:
        type: string
      fire:
        type: string
      ice:
        type: string
      thunder:
        type: string
      water:
        type: string
    type: object
  skill.MessageResponse:
    properties:
      message:
        type: string
    type: object
  skill.ResponseSkill:
    properties:
      description:
        type: string
      id:
        type: string
      level:
        items:
          $ref: '#/definitions/skill.ResponseSkillLevel'
        type: array
      name:
        type: string
    type: object
  skill.ResponseSkillLevel:
    additionalProperties:
      type: string
    type: object
  skill.Skill:
    properties:
      description:
        type: string
      id:
        type: string
      level:
        items:
          $ref: '#/definitions/skill.ResponseSkillLevel'
        type: array
      name:
        type: string
    type: object
  skill.Skills:
    properties:
      skills:
        items:
          $ref: '#/definitions/skill.ResponseSkill'
        type: array
    type: object
  weapon.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  weapon.ListWeaponsResponse:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total_count:
        type: integer
      weapons:
        items:
          $ref: '#/definitions/weapon.WeaponDetailResponse'
        type: array
    type: object
  weapon.WeaponDetailResponse:
    properties:
      attack:
        type: string
      critical:
        type: string
      description:
        type: string
      element_attack:
        type: string
      image_url:
        type: string
      name:
        type: string
      rare:
        type: string
      sharpness:
        type: string
      weapon_id:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: https://mh-api-v2-8aznfogc.an.gateway.dev/
info:
  contact: {}
  description: モンスターハンターAPI
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: MH-API
  version: v0.1.0
paths:
  /armors:
    get:
      consumes:
      - application/json
      description: 全ての防具のリストを返します。
      produces:
      - application/json
      responses:
        "200":
          description: 防具のリスト
          schema:
            $ref: '#/definitions/armor.ListArmorsResponse'
        "500":
          description: サーバ内部エラー
          schema:
            $ref: '#/definitions/armor.ErrorResponse'
      summary: 防具一覧を取得します
      tags:
      - Armors
  /armors/{id}:
    get:
      consumes:
      - application/json
      description: 指定されたIDの防具の詳細を返します。
      parameters:
      - description: 防具ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 防具の詳細
          schema:
            $ref: '#/definitions/armor.ArmorDetailResponse'
        "400":
          description: リクエストパラメータが不正な場合
          schema:
            $ref: '#/definitions/armor.ErrorResponse'
        "404":
          description: 防具が見つからない場合
          schema:
            $ref: '#/definitions/armor.ErrorResponse'
        "500":
          description: サーバ内部エラー
          schema:
            $ref: '#/definitions/armor.ErrorResponse'
      summary: 防具詳細を取得します
      tags:
      - Armors
  /items:
    get:
      description: 全てのアイテム名とIDの一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/item.Items'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/item.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/item.MessageResponse'
      summary: アイテム名の一覧を取得する
      tags:
      - アイテム検索
  /items/{itemId}:
    get:
      consumes:
      - application/json
      description: アイテムを検索して、条件に合致するアイテムを1件取得する
      parameters:
      - description: アイテムID
        in: path
        name: itemId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/item.Item'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/item.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/item.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/item.MessageResponse'
      summary: アイテム検索（1件）
      tags:
      - アイテム検索
  /items/monsters/{monsterId}:
    get:
      consumes:
      - application/json
      description: 指定のアイテムが取得可能なモンスターの一覧
      parameters:
      - description: モンスターID
        in: path
        name: monsterId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/item.ItemsByMonster'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/item.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/item.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/item.MessageResponse'
      summary: アイテム検索（モンスター別）
      tags:
      - アイテム検索
  /monsters:
    get:
      consumes:
      - application/json
      description: モンスターを検索して、条件に合致するモンスターを複数件取得する
      parameters:
      - in: query
        name: MonsterIds
        type: string
      - in: query
        name: MonsterName
        type: string
      - in: query
        name: UsageElement
        type: string
      - in: query
        name: WeaknessElement
        type: string
      - in: query
        minimum: 0
        name: limit
        type: integer
      - in: query
        minimum: 0
        name: offset
        type: integer
      - enum:
        - asc
        - desc
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/monster.Monsters'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/monster.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/monster.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/monster.MessageResponse'
      summary: モンスター検索（複数件）
      tags:
      - モンスター検索
  /monsters/{id}:
    get:
      consumes:
      - application/json
      description: モンスターを検索して、条件に合致するモンスターを1件取得する
      parameters:
      - description: モンスターID
        in: path
        name: request
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/monster.Monster'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/monster.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/monster.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/monster.MessageResponse'
      summary: モンスター検索（1件）
      tags:
      - モンスター検索
  /skills:
    get:
      description: 全てのスキルとその情報の一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/skill.Skills'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/skill.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/skill.MessageResponse'
      summary: スキル一覧を取得する
      tags:
      - スキル検索
  /skills/{skillId}:
    get:
      consumes:
      - application/json
      description: スキルを検索して、条件に合致するスキルを1件取得する
      parameters:
      - description: スキルID
        in: path
        name: skillId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/skill.Skill'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/skill.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/skill.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/skill.MessageResponse'
      summary: スキル検索（1件）
      tags:
      - スキル検索
  /weapons:
    get:
      consumes:
      - application/json
      description: 指定されたクエリパラメータに基づいて武器のリストを返します。
      parameters:
      - description: 武器ID (完全一致)
        in: query
        name: weapon_id
        type: string
      - description: 武器名 (部分一致を想定)
        in: query
        name: name
        type: string
      - default: 20
        description: 取得件数
        in: query
        name: limit
        type: integer
      - default: 0
        description: 取得開始位置
        in: query
        name: offset
        type: integer
      - description: ソートフィールド (asc/desc)
        in: query
        name: sort
        type: string
      - description: ソート順 (0:昇順, 1:降順)
        in: query
        name: order
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 武器のリストとページネーション情報
          schema:
            $ref: '#/definitions/weapon.ListWeaponsResponse'
        "400":
          description: リクエストパラメータが不正な場合
          schema:
            $ref: '#/definitions/weapon.ErrorResponse'
        "500":
          description: サーバ内部エラー
          schema:
            $ref: '#/definitions/weapon.ErrorResponse'
      summary: 武器リストを検索します (Gin版)
      tags:
      - Weapons
swagger: "2.0"
