// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package weapons

import (
	"context"
	"sync"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked Repository
//		mockedRepository := &RepositoryMock{
//			FindFunc: func(ctx context.Context, params SearchParams) (*SearchResult, error) {
//				panic("mock out the Find method")
//			},
//		}
//
//		// use mockedRepository in code that requires Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, params SearchParams) (*SearchResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params SearchParams
		}
	}
	lockFind sync.RWMutex
}

// Find calls FindFunc.
func (mock *RepositoryMock) Find(ctx context.Context, params SearchParams) (*SearchResult, error) {
	if mock.FindFunc == nil {
		panic("RepositoryMock.FindFunc: method is nil but Repository.Find was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params SearchParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, params)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedRepository.FindCalls())
func (mock *RepositoryMock) FindCalls() []struct {
	Ctx    context.Context
	Params SearchParams
} {
	var calls []struct {
		Ctx    context.Context
		Params SearchParams
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}
