name: golang-ci
on:
  push:
    branches:
      - "main"
    paths:
      - "**.go"
      - .github/workflows/ci.yml
      - ".golangci.yml"
  pull_request:
    paths:
      - "**.go"
      - ".github/workflows/ci.yml"
      - ".golangci.yml"
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=5m --config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
