# DBに新規データを入れるため
on:
  push:
    branches:
    paths:
      - "data/input/data.csv"
  
jobs:
  create-json:
    name: create-json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: create json
        uses: ./cmd/csvtojson
      
      - name: display json
        uses: cat data/output/data.json | jq