# DBに新規データを入れるため
name: Create Data
on:
  push:
    branches:
      - main
    paths:
      - "data/input/data.csv"
env:
  client_id: ${{ secrets.clientid }}
  clientsecret: ${{ secrets.clientsecrets }}
  audienceurl: ${{ secrets.audienceurl }}
  granttype: ${{ secrets.granttype }}

jobs:
  create-json:
    name: create-json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: create json
        run: ./cmd/csvtojson

      - name: display json
        run: cat data/output/data.json | jq

      - name: get authentication token
        run: |
          token=$(curl -X POST \
          -H "Content-type: application/json" \
          -d '{"client_id":"${{ env.clientid }}","client_secret":"${{ env.clientsecret }}","audience":"${{ env.audienceurl }}","grant_type":"${{ env.granttype }}"}'\
          https://dev-8pmkik25y0obts0r.us.auth0.com/oauth/token | jq -r '.access_token')
          echo "TOKEN=$(token)" >> $GITHUB_ENV
      - name: call API
        run: |
          curl -X POST \
          -b "token={{ env.TOKEN }}" \
          --data @./data/output/data.json \
          http://localhost:8080/v1/auth/monsters/json
