# DBに新規データを入れるため
name: Create Data
on:
  push:
    branches:
      - main
    paths:
      - "data/input/data.csv"
      - ".github/workflows/create_record.yml"
      - "cmd/csvtojson"
env:
  clientid: ${{ secrets.CLIENTID }}
  clientsecret: ${{ secrets.CLIENTSECRET }}
  audienceurl: ${{ secrets.AUDIENCEURL }}
  granttype: ${{ secrets.GRANTTYPE }}

jobs:
  create-json:
    name: create-json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: create json
        run: ./cmd/csvtojson

      - name: display json
        run: cat data/output/data.json | jq

      - name: get authentication token
        run: |
          echo TOKEN=$(curl -X POST \
          -H "Content-type: application/json" \
          -d '{"client_id":"${{ secrets.CLIENTID }}","client_secret":"${{ secrets.CLIENTSECRET }}","audience":"${{ secrets.AUDIENCEURL }}","grant_type":"${{ secrets.GRANTTYPE }}"}' \
          https://dev-8pmkik25y0obts0r.us.auth0.com/oauth/token | jq -r '.access_token') >> $GITHUB_ENV

      - name: call API
        run: |
          curl -request POST \
          --url ${{ env.audienceurl }}/v1/monsters/json \
          --header 'authorization: Bearer $TOKEN' \
          --data @./data/output/data.json
