# DBに新規データを入れるため
on:
  push:
    branches:
      - main
    paths:
      - "data/input/data.csv"
  
jobs:
  create-json:
    name: create-json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: create json
        run: ./cmd/csvtojson
      
      - name: display json
        run: cat data/output/data.json | jq

      - name: get authentication token
        run: |
              toke=$(curl -X POST \
              -H "Content-type: application/json" \
              -d '{"name":"${{ secrets.ADMIN }}","password":"${{ secrets.PASSOWRD }}"}' \
              http://localhost:8080/v1/auth　| jq -r '.token')
              echo "TOKEN=$(token)" >> $GITHUB_ENV
      - name: call API  
        run: |
              curl -X POST \
              -b "token={{ env.TOKEN }}" \
              --data @./data/output/data.json \
              http://localhost:8080/v1/auth/monsters/json