name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  PORT: ${{ secrets.PORT }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
  IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build a docker image
        run: docker build --platform linux/amd64 -t ${{ env.IMAGE }} --target deploy ./

      - name: Push the docker image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy ${{ env.SERVICE_NAME }} \
              --image ${{ env.IMAGE }} \
              --project ${{ env.GCP_PROJECT_ID }} \
              --region ${{ env.GCP_REGION }} \
              --platform=managed \
              --allow-unauthenticated \
              --quiet \
              --update-secrets=DB_HOST \
              --update-secrets=DB_PORT \
              --update-secrets=DB_USER \
              --update-secrets=DB_PASSWORD \
              --update-secrets=DB_NAME \
              --update-secrets=USER \
              --update-secrets=PASSWORD
