name: Deploy apigateway

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*"
    paths:
      - "doc/openapi/apigateway.yml"

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  GCP_API: ${{ secrets.GCP_API }}
  GCP_API_CONFIG: ${{ secrets.GCP_API_CONFIG }}
  GCP_API_GATEWAY: ${{ secrets.GCP_API_GATEWAY }}
  GCP_TAG: ${{ github.sha }}

jobs:
  deploy-to-apigateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy Config apigateway
        run: |
          gcloud api-gateway api-configs create ${{ env.GCP_API_CONFIG }}-${{ env.GCP_TAG }} --api=${{ env.GCP_API_GATEWAY }} --openapi-spec=./doc/openapi/apigateway.yml --backend-auth-service-account=${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Deploy apigateway
        run: |
          gcloud api-gateway gateways update ${{ env.GCP_API }} --project=${{ env.GCP_PROJECT_ID }} --api-config=${{ env.GCP_API_CONFIG }}-${{ env.GCP_TAG }} --api=${{ env.GCP_API_GATEWAY }} --location=${{ env.GCP_REGION }}
