name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - "doc/openapi/apigateway.yml"

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  GCP_API: ${{ secrets.GCP_API }}
  GCP_API_CONFIG: ${{ secrets.GCP_API_CONFIG }}
  GCP_API_GATEWAY: ${{ secrets.GCP_API_GATEWAY }}

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy Config apigateway
        run: |
          gcloud api-gateway api-configs create ${{ GCP_API_CONFIG }}-${{ github.sha }} --api=${{ GCP_API_GATEWAY }} --openapi-spec=./doc/openapi/apigateway.yml

      - name: Deploy apigateway
        run: |
          gcloud api-gateway gateways update ${{ GCP_API }} --project=${{ GCP_PROJECT_ID }} --api-config=${{ GCP_API_CONFIG }} --api=${{ GCP_API_GATEWAY }} --location=${{ GCP_REGION }}
            

