name: lint and test
on:
  pull_request:
    branches:
      - "main"
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_version: v1.64.8
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=5m --config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
          
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24
      
      - name: run Docker
        run: |
          DATABASE_URL="mh-api:P@ssw0rd@tcp(mh-api-dbsrv01)/ci?charset=utf8&parseTime=True&loc=Local" make compose-up
          DATABASE_URL="mh-api:P@ssw0rd@tcp(127.0.0.1:3306)/ci?charset=utf8&parseTime=True&loc=Local" make migrate-up


      - name: testing
        run: |
          go test ./... -parallel=1 -coverprofile=coverage.out

      - name: create report
        uses: k1LoW/octocov-action@v0
