name: Open API Spec

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/spec.yml"
      - "doc/openapi/swagger.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Check out
        uses: actions/checkout@v3

      - name: Build ReDoc HTML
        run: |
          npm install -g redoc-cli
          redoc-cli bundle doc/openapi/swagger.yaml
          mkdir pages
          mv redoc-static.html pages/spec.html

      - uses: actions/upload-artifact@v3
        with:
          name: fastapi_doc
          path: pages
      - uses: actions/upload-pages-artifact@v1
        with:
          path: pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
