name: Test
on:
  push:
    paths:
      - "**.go"
      - .github/workflows/test.yml
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/test.yml

jobs:
  golang-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: testing
        run: go test ./... -coverprofile=coverage.out

      - name: create report
        uses: k1LoW/octocov-action@v0
