name: Test
on:
  pull_request:
    branches:
    - release
jobs:
  golang-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing
        run: go test ./... -coverprofile=coverage.out
      - name: create report
        uses: k1LoW/octocov-action@v0