name: Test
on:
  push:
    branches:
      - "main"
    paths:
      - "**.go"
      - .github/workflows/test.yml
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/test.yml

jobs:
  golang-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      
      - name: run Docker
        run: |
          cd environment
          docker compose up -d mh-api-dbsrv01

      - name: testing
        run: |
          go test ./... -parallel=1 -coverprofile=coverage.out

      - name: create report
        uses: k1LoW/octocov-action@v0
